[entryPoints]
  [entryPoints.web]
  address = "0.0.0.0:80"
##  [entryPoints.web.http]
##    [entryPoints.web.http.redirections]
##      [entryPoints.web.http.redirections.entryPoint]
##        to = "websecure"
##        scheme = "https"
##        permanent = true
  [entryPoints.websecure]
  address = ":443"
  [entryPoints.websecure.http.tls]
    certResolver = "myresolver"

[api]
  dashboard = true
  insecure = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false
  network = "traefik_local_net"

[log]
  level = "DEBUG"

## Dynamic configuration
[web.routers]
  [web.routers.Router-1]
    # won't listen to entry point web
    entryPoints = ["web", "websecure"]
    rule = "Host(`jeedom.nico.si`)"
    service = "jeedomprod"

## Dynamic configuration
[web.services]
  [web.services.jeedomprod.loadBalancer]
    [[web.services.jeedomprod.loadBalancer.servers]]
      url = "http://192.168.1.25:80"

[certificatesResolvers.myresolver.acme]
  email = "nicolas_gras@hotmail.com"
  storage = "/letsencrypt/acme.json"
  # staging-v02
  # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.myresolver.acme.dnsChallenge]
    provider = "ovh"
    delayBeforeCheck = 10
  # [certificatesResolvers.myresolver.acme.httpChallenge]
    # used during the challenge
    # entryPoint = "web"
  