version: "3"
services:
  certbot:
    build: .
    environment:
      DOMAIN: domain.com
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./log:/var/log/letsencrypt
      - ./.ovhapi:/app/.ovhapi
    command: >-
      certbot certonly --dns-ovh --dns-ovh-credentials .ovhapi
      --non-interactive --agree-tos --email email@example.com
      -d subdomain.example.com --test-cert --dry-run -v
