version: "3"
services:
  certbot:
    build: .
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./log:/var/log/letsencrypt
    command: certbot certonly --dns-ovh --dns-ovh-credentials .ovhapi --non-interactive --agree-tos --email nicolas_gras@hotmail.com -d portainer.nico.si
